---
kind: pipeline
type: kubernetes
name: build

steps:

  - name: kube config
    image: quay.io/ukhomeofficedigital/kd
    environment:
      KUBE_CLUSTER: acp-notprod
      KUBE_NAMESPACE: cs-dev
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      KUBE_TOKEN:
        from_secret: cs_notprod
    commands:
      - ./setup-kube.sh
    depends_on:
      - clone

  - name: config cs dev
    image: alpine/helm
    environment:
      KUBE_CLUSTER: acp-notprod
      KUBE_NAMESPACE: cs-dev
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      KUBE_TOKEN:
        from_secret: cs_notprod
      VERSION: build-${DRONE_BUILD_NUMBER}
    commands:
      - ./deploy.sh
    when:
      branch: main
      event:
        - push
        - tag
    depends_on:
      - kube config
