---
kind: pipeline
type: kubernetes
name: build

steps:

  - name: kube config
    image: alpine/k8s
    environment:
      KUBE_CLUSTER: acp-notprod
      KUBE_NAMESPACE: cs-dev
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      KUBE_TOKEN:
        from_secret: cs_notprod
      VERSION: 0.0.1
    commands:
      - ./setup-kube.sh
      - ./deploy.sh
    depends_on:
      - clone
    when:
      branch: main
      event:
        - push
        - tag
