---
kind: pipeline
type: kubernetes
name: deploy tag
trigger:
  event:
    - tag
  branch:
    - main

steps:
  - name: config
    image: quay.io/ukhomeofficedigital/kd:v1.20.15
    environment:
      KUBE_CLUSTER: acp-notprod
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      KUBE_TOKEN:
        from_secret: cs_notprod
    commands:
      - ./kube/setup-kube.sh
    volumes:
      - name: kube
        path: /root/.kube
    depends_on:
      - clone

  - &deploy
    name: cs-dev
    image: alpine/helm:3.9.4
    environment:
      KUBE_NAMESPACE: cs-dev
      VERSION: ${DRONE_TAG}
      VALUES_FILE: '--values ./helm/values-notprod.yaml'
    commands:
      - ./kube/helm-deploy.sh
    volumes:
      - name: kube
        path: /root/.kube
    depends_on:
      - config

  - <<: *deploy
    name: wcs-dev
    environment:
      KUBE_NAMESPACE: wcs-dev

volumes:
  - name: kube
    temp: {}

---
kind: pipeline
type: kubernetes
name: deploy
trigger:
  event:
    - promote

steps:
    - name: checkout
      image: alpine/git
      commands:
        - git fetch --tags
        - git checkout $${VERSION}

    - &config
      name: prod config
      image: quay.io/ukhomeofficedigital/kd:v1.20.15
      environment:
        KUBE_CLUSTER: acp-prod
        KUBE_SERVER: https://kube-api-prod.prod.acp.homeoffice.gov.uk
        KUBE_TOKEN:
          from_secret: cs_prod
      commands:
        - cd kube
        - ./setup-kube.sh
      volumes:
        - name: kube
          path: /root/.kube
      depends_on:
        - checkout

    - <<: *config
      name: notprod config
      environment:
        KUBE_CLUSTER: acp-notprod
        KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
        KUBE_TOKEN:
          from_secret: cs_notprod

    - &deploy
      name: prod
      image: alpine/helm:3.9.4
      environment:
        KUBE_NAMESPACE: ${DRONE_DEPLOY_TO}
        VERSION: ${DRONE_TAG}
      commands:
        - ./kube/helm-deploy.sh
      volumes:
        - name: kube
          path: /root/.kube
      depends_on:
        - prod config
      when:
        target:
          - '*-prod'

    - <<: *deploy
      name: notprod
      environment:
        VALUES_FILE: '--values ./helm/values-notprod.yaml'
      depends_on:
        - notprod config
      when:
        target:
          - 'cs-*'
          - 'wcs-*'

    - <<: *deploy
      name: wcs-qa
      environment:
        KUBE_NAMESPACE: wcs-qa
        VALUES_FILE: '--values ./helm/values-notprod.yaml'
      depends_on:
        - notprod config
      when:
        target:
          - release

    - <<: *deploy
      name: cs-qa
      environment:
        KUBE_NAMESPACE: cs-qa
        VALUES_FILE: '--values ./helm/values-notprod.yaml'
      depends_on:
        - notprod config
      when:
        target:
          - release
