---
kind: pipeline
type: kubernetes
name: deploy tag
trigger:
  event:
    - tag
  branch:
    - main

steps:
  - &deploy
    name: cs-dev
    image: quay.io/ukhomeofficedigital/helm
    environment:
      KUBE_CLUSTER_NAME: acp-notprod
      KUBE_NAMESPACE: cs-dev
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      KUBE_TOKEN:
        from_secret: cs_notprod
      VALUES_FILE: '--values ./helm/values-notprod.yaml'
      VERSION: ${DRONE_TAG}
    commands:
      - /setup-kubeconfig.sh
      - cd ./helm
      - ./helm-deploy.sh
    depends_on:
      - clone

  - <<: *deploy
    name: wcs-dev
    environment:
      KUBE_NAMESPACE: wcs-dev
    depends_on:
      - cs-dev
---
kind: pipeline
type: kubernetes
name: deploy
trigger:
  event:
    - promote

steps:
    - name: checkout
      image: alpine/git
      commands:
        - git fetch --tags
        - git checkout $${VERSION}

    - name: prod deploy
      image: quay.io/ukhomeofficedigital/helm
      environment:
        KUBE_CLUSTER_NAME: acp-prod
        KUBE_NAMESPACE: ${DRONE_DEPLOY_TO}
        KUBE_SERVER: https://kube-api-prod.prod.acp.homeoffice.gov.uk
        KUBE_TOKEN:
          from_secret: cs_prod
      commands:
        - /setup-kubeconfig.sh
        - cd ./helm
        - ./helm/helm-deploy.sh
      depends_on:
        - checkout
      when:
        target:
          - '*-prod'
          - '*-preprod'

    - &deploy
      name: notprod deploy
      image: quay.io/ukhomeofficedigital/helm
      environment:
        KUBE_CLUSTER_NAME: acp-notprod
        KUBE_NAMESPACE: ${DRONE_DEPLOY_TO}
        KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
        KUBE_TOKEN:
          from_secret: cs_notprod
        VALUES_FILE: '--values ./helm/values-notprod.yaml'
      commands:
        - /setup-kubeconfig.sh
        - cd ./helm
        - ./helm/helm-deploy.sh
      depends_on:
        - checkout
      when:
        target:
          exclude:
            - '*-prod'
            - '*-preprod'

    - <<: *deploy
      name: wcs-qa
      environment:
        KUBE_NAMESPACE: wcs-qa
      when:
        target:
          - release

    - <<: *deploy
      name: cs-qa
      environment:
        KUBE_NAMESPACE: cs-qa
      when:
        target:
          - release
