---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-backend-polciy
spec:
  podSelector:
    matchLabels:
      role: hocs-backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 10443
      protocol: TCP
    from:
    - podSelector:
        matchLabels:
          role: hocs-frontend
    - podSelector:
        matchLabels:
          role: hocs-backend
  egress:
  - to:
    - namespaceSelector: {}
  - ports:
    - port: 5432
      protocol: TCP
