---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hocs-outbound-proxy-{{.KUBE_NAMESPACE}}
  version: {{.VERSION}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hocs-outbound-proxy
        version: {{.VERSION}}
    spec:
      containers:
        - name: proxy
          image: quay.io/ukhomeofficedigital/squidproxy:v0.0.4
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
          ports:
            - name: http
              containerPort: 3129
          resources:
            limits:
              memory: "256Mi"
              cpu: "1"
            requests:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
            - name: hocs-outbound-proxy-config
              mountPath: /etc/squid
      volumes:
        - name: hocs-outbound-proxy-config
          configMap:
            name: hocs-outbound-proxy-config
