---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-backend-policy
spec:
  podSelector:
    matchLabels:
      role: hocs-backend-{{.KUBE_NAMESPACE}}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 10443
      protocol: TCP
    from:
    - podSelector:
        matchLabels:
          role: hocs-frontend-{{.KUBE_NAMESPACE}}
    - podSelector:
        matchLabels:
          role: hocs-backend-{{.KUBE_NAMESPACE}}
  egress:
  - to:
    - namespaceSelector: {}
  - ports:
    - port: 5432
      protocol: TCP
