apiVersion: v1
kind: ConfigMap
metadata:
  name: hocs-outbound-proxy-config
data:
  squid.conf: |
    # Local configuration
    acl localnet src 10.0.0.0/8

    # ACL ALLOWED PORTS
    acl SSL_ports port 443

    acl notify dstdomain .notifications.service.gov.uk  # GOV.UK Notify Service
    acl keycloak dstdomain {{.KC_URL}}                  # Development Keycloak instance

    acl CONNECT method CONNECT

    # PID file location
    pid_filename /home/proxy/squid.pid


    # Deny requests to all but SSL ports
    http_access deny !SSL_ports

    # Deny CONNECT to other than secure SSL ports
    http_access deny CONNECT !SSL_ports

    # Only allow cachemgr access from localhost
    http_access allow manager localhost
    http_access deny manager

    http_access deny to_localhost

    http_access allow localnet notify
    http_access allow localnet keycloak

    # And finally deny all other access to this proxy
    http_access deny all

    # LISTENING PORT
    http_port 3129

    # ADDITIONAL TWEAKS
    cache deny all
    forwarded_for delete
    httpd_suppress_version_string on
    via off

    # LOGGING
    logfile_rotate 0
    logformat squid {"logtime":"%tl", response_time":%tr, "src_ip":"%>a", "squid_request_status":"%Ss", "http_status_code":%>Hs, "reply_size_include_header":%<st, "http_method":"%rm", "request_url":"%ru", "request_path":"%rp", "squid":"%Sh", "dst_ip":"%<a", "content_type":"%mt"}
    cache_log stdio:/dev/stdout
    access_log stdio:/dev/stdout
    cache_store_log stdio:/dev/stdout
  mime.conf: |
    # Empty file
