---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hocs-backend-policy
spec:
  podSelector:
    matchLabels:
      role: hocs-backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: hocs-frontend
    - podSelector:
        matchLabels:
          role: hocs-backend
    ports:
    - port: 10443
      protocol: TCP
  egress:
  - to:
    - ipBlock:
      cidr: {{.RDS_CIDR}}
    ports:
    - port: 5432
      protocol: TCP

