apiVersion: v1
kind: ConfigMap
metadata:
  name: hocs-outbound-proxy-config
data:
  squid.conf: |
    # Local configuration
    acl localnet src 10.0.0.0/8

    # ACL ALLOWED PORTS
    acl Safe_ports port 80                # HTTP
    acl Safe_ports port 443                # HTTPS
    acl Safe_ports port 5432                # Postgres
    acl SSL_ports port 443                 # HTTPS

    acl notify dstdomain .notifications.service.gov.uk # GOV.UK Notify Service
    acl keycloak dstdomain {{.KC_URL}} # Development Keycloak instance
    acl aws_sqs dstdomain sqs.eu-west-2.amazonaws.com # aws sqs
    acl aws_s3 dstdomain s3.eu-west-2.amazonaws.com # aws s3
    acl uk_parliament dstdomain data.parliament.uk # UK Parliament
    acl scot_parliament dstdomain data.parliament.scot # Scotish Parliament
    acl ni_parliament dstdomain data.niassembly.gov.uk # NI Parliament
    acl eu_parliament dstdomain europarl.europa.eu # EU Parliament
    acl wales_parliament dstdomain senedd.assembly.wales # Welsh Assembley
    acl clamav dstdomain db.uk.clamav.net #Clam av database

    acl CONNECT method CONNECT

    # PID file location
    pid_filename /home/proxy/squid.pid

    # Deny requests to all but Safe ports
    http_access deny !Safe_ports

    # Deny CONNECT to other than secure SSL ports
    http_access deny CONNECT !Safe_ports

    # Only allow cachemgr access from localhost
    http_access allow manager localhost
    http_access deny manager

    http_access deny to_localhost

    http_access allow localnet
    http_access allow localnet notify
    http_access allow localnet keycloak
    http_access allow localnet aws_sqs
    http_access allow localnet aws_s3
    http_access allow localnet uk_parliament
    http_access allow localnet scot_parliament
    http_access allow localnet wales_parliament
    http_access allow localnet eu_parliament
    http_access allow localnet ni_parliament
    http_access allow localnet clamav

    # And finally deny all other access to this proxy
    http_access deny all

    # LISTENING PORT
    http_port 3129

    # ADDITIONAL TWEAKS
    cache deny all
    forwarded_for delete
    httpd_suppress_version_string on
    via off

    # LOGGING
    logfile_rotate 0
    logformat squid {"logtime":"%tl", response_time":%tr, "src_ip":"%>a", "squid_request_status":"%Ss", "http_status_code":%>Hs, "reply_size_include_header":%<st, "http_method":"%rm", "request_url":"%ru", "request_path":"%rp", "squid":"%Sh", "dst_ip":"%<a", "content_type":"%mt"}
    cache_log stdio:/dev/stdout
    access_log stdio:/dev/stdout
    cache_store_log stdio:/dev/stdout
  mime.conf: |
    # Empty file
