---
hocs-generic-service:
  nameOverride: hocs-outbound-proxy

  deployment:
    replicas: 1
    annotations:
      downscaler/downtime: "Mon-Sun 00:00-04:50 Europe/London,Mon-Sun 23:10-24:00 Europe/London"

  service:
    port: 31290
    targetPort: 3129

  truststore:
    enabled: false

  proxy:
    enabled: false

  app:
    image:
      repository: quay.io/ukhomeofficedigital/hocs-outbound-proxy
    selectorRole: hocs-outbound-proxy
    resources:
      limits:
        cpu: 300m
        memory: 96Mi
      requests:
        memory: 96Mi
