---
hocs-backend-service:
  minReplicas: 1
  maxReplicas: 1

  deploymentAnnotations:
    downscaler/uptime: "Mon-Sun 07:50-18:10 Europe/London"

  app:
    resources:
       limits:
         cpu: 200m
         memory: 96Mi
