name: 'Deploy notprod'

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Deploy to environment'
        required: true
        type: choice
        default: 'cs-dev'
        options:
          - cs-dev
          - hocs-qax

jobs:
  publish:
    name: 'Deploy'
    runs-on: self-hosted

    steps:
      - name: Configure Kube
        if: ${{ inputs.components != '' }}
        run: ./kube/setup_kube.sh
        shell: bash

      - name: Helm Deploy
        if: ${{ inputs.components != '' }}
        run: ./kube/helm-deploy.sh
        env:
          KUBE_NAMESPACE: ${{ github.event.inputs.namespace }}
          VERSION: 1.0.0
          VALUES_FILE: '--values ./helm/values-notprod.yaml'
        shell: bash
