

name: 'local runner Checker'
on:
  pull_request:
    types: [ labeled, unlabeled, opened, reopened, synchronize ]
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: 'Check For Valid Label'
    runs-on: local-runner

    steps:
      - name: Check label value
        id: label
        uses: UKHomeOffice/match-label-action@v1
        with:
          labels: minor,major,patch,skip-release
          mode: singular

      - name: Calculate SemVer value
        if: contains(steps.label.outputs.matchedLabels, 'skip-release') == false
        uses: UKHomeOffice/semver-calculate-action@v1
        with:
          increment: ${{ steps.label.outputs.matchedLabels }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_to_highest: ${{ github.base_ref == 'main' }}
